version: '1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  worker:
    build: ../worker
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongo
      - redis
    privileged: true