name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker build
        uses: docker/setup-buildx-action@v2
      
      - name: Docker compose
        uses: docker/setup-qemu-action@v2

      - name: Docker compose check
        uses: docker compose version

      - name: Run Integration test
        uses: cd server && npm run test:integration